// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        newMethod();
      case TargetPlatform.windows:
        newMethod();
      default:
        newMethod();
    }
  }

  static Never newMethod() {
    return throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGabRbPizq7naS5513b4Hoo7ynME8sa88',
    appId: '1:889955445816:web:7b9ee3bcf059a8f3454acd',
    messagingSenderId: '889955445816',
    projectId: 'shreejikhakhra-87245',
    authDomain: 'shreejikhakhra-87245.firebaseapp.com',
    storageBucket: 'shreejikhakhra-87245.firebasestorage.app',
    measurementId: 'G-FZ7PK2VBXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqcOjyXblydpzK0NpM3X9R7Rhhsn8axQk',
    appId: '1:889955445816:android:d58e2a0acaa6ed09454acd',
    messagingSenderId: '889955445816',
    projectId: 'shreejikhakhra-87245',
    storageBucket: 'shreejikhakhra-87245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzbCxG3_hdzAgcgdYX-RPT9csuNnYFLwQ',
    appId: '1:889955445816:ios:d08ca35c43d4e34f454acd',
    messagingSenderId: '889955445816',
    projectId: 'shreejikhakhra-87245',
    storageBucket: 'shreejikhakhra-87245.firebasestorage.app',
    iosBundleId: 'com.example.shreejikhakhra',
  );
}
